---
title: "Data Organization"
author: "Anna Talucci"
date: "June 27, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# overview

GEE data 

Climate data from Terra Climate 

Temperature (degrees celcius) scale = 0.1
precipitation (mm) no scaling

# Packages

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(readr)
```



# Data

## Temerature

### Winter

```{r}
win_temp_path <- "../data/gee_perimeter/winter_temp"   # path to the data
win_temp_files <- dir(win_temp_path, pattern = "*.csv") # get file names
```

```{r}
win_temp_data <- win_temp_files %>%
  # read in all the files, appending the path before the filename
  map(~ read_csv(file.path(win_temp_path, .))) %>% 
  reduce(rbind)
win_temp_data
```

```{r}
win_temp_data %>% summarise_all(~ sum(is.na(.)))
```

```{r}
win_temp_sel = win_temp_data %>% 
                      dplyr::select(ID_obj:mean) %>%
                      rename(wtr_temp = mean)
                      

head(win_temp_sel)
```


### Spring

```{r}
spr_temp_path <- "../data/gee_perimeter/spring_temp"   # path to the data
spr_temp_files <- dir(spr_temp_path, pattern = "*.csv") # get file names
```

```{r}
spr_temp_data <- spr_temp_files %>%
  # read in all the files, appending the path before the filename
  map(~ read_csv(file.path(spr_temp_path, .))) %>% 
  reduce(rbind)
spr_temp_data
```

```{r}
spr_temp_data %>% summarise_all(~ sum(is.na(.)))
```

```{r}
spr_temp_sel = spr_temp_data %>% 
                      dplyr::select(ID_obj:mean) %>%
                      rename(spr_temp = mean)
head(spr_temp_sel)
```

### Summer

```{r}
smr_temp_path <- "../data/gee_perimeter/summer_temp"   # path to the data
smr_temp_files <- dir(smr_temp_path, pattern = "*.csv") # get file names
```

```{r}
smr_temp_data <- smr_temp_files %>%
  # read in all the files, appending the path before the filename
  map(~ read_csv(file.path(smr_temp_path, .))) %>% 
  reduce(rbind)
smr_temp_data
```
```{r}
smr_temp_data %>% summarise_all(~ sum(is.na(.)))
```
```{r}
smr_temp_sel = smr_temp_data %>% 
                      dplyr::select(ID_obj:mean) %>%
                      rename(smr_temp = mean)
head(smr_temp_sel)
```

### Combine Temperature data

```{r}
temp_w_sp = merge(win_temp_sel, spr_temp_sel, by = c("ID_obj", "area_ha", "area_m", "fire_yr"))
df_temp = merge(temp_w_sp, smr_temp_sel, by = c("ID_obj", "area_ha", "area_m", "fire_yr"))
```

```{r}
df_temp
```


## Precipitation


### Winter
```{r}
win_pr_path <- "../data/gee_perimeter/winter_pr"   # path to the data
win_pr_files <- dir(win_pr_path, pattern = "*.csv") # get file names
```

```{r}
win_pr_data <- win_pr_files %>%
  # read in all the files, appending the path before the filename
  map(~ read_csv(file.path(win_pr_path, .))) %>% 
  reduce(rbind)
win_pr_data
```

```{r}
win_pr_data %>% summarise_all(~ sum(is.na(.)))
```

```{r}
win_pr_sel = win_pr_data %>% 
                      dplyr::select(ID_obj:mean) %>%
                      rename(wtr_pr = mean)
head(win_pr_sel)
```

### Spring

```{r}
spr_pr_path <- "../data/gee_perimeter/spring_pr"   # path to the data
spr_pr_files <- dir(spr_pr_path, pattern = "*.csv") # get file names
```

```{r}
spr_pr_data <- spr_pr_files %>%
  # read in all the files, appending the path before the filename
  map(~ read_csv(file.path(spr_pr_path, .))) %>% 
  reduce(rbind)
spr_pr_data
```

```{r}
spr_pr_data %>% summarise_all(~ sum(is.na(.)))
```

```{r}
spr_pr_sel = spr_pr_data %>% 
                      dplyr::select(ID_obj:mean) %>%
                      rename(spr_pr = mean)
head(spr_pr_sel)
```

### Summer

```{r}
smr_pr_path <- "../data/gee_perimeter/summer_pr"   # path to the data
smr_pr_files <- dir(smr_pr_path, pattern = "*.csv") # get file names
```

```{r}
smr_pr_data <- smr_pr_files %>%
  # read in all the files, appending the path before the filename
  map(~ read_csv(file.path(smr_pr_path, .))) %>% 
  reduce(rbind)
smr_pr_data
```

```{r}
smr_pr_data %>% summarise_all(~ sum(is.na(.)))
```

```{r}
smr_pr_sel = smr_pr_data %>% 
                      dplyr::select(ID_obj:mean) %>%
                      rename(smr_pr = mean)
head(smr_pr_sel)
```

### Combine PR data

```{r}
pr_w_sp = merge(win_pr_sel, spr_pr_sel, by = c("ID_obj", "area_ha", "area_m", "fire_yr"))
df_pr = merge(pr_w_sp, smr_pr_sel, by = c("ID_obj", "area_ha", "area_m", "fire_yr"))
```

```{r}
df_pr
```

## Combine Temp and PR

```{r}
df_temp_pr = merge(df_temp, df_pr, by = c("ID_obj", "area_ha", "area_m", "fire_yr"))

```

```{r}
df_temp_pr
```

## Snow


```{r}
snow_path <- "../data/gee_perimeter/snow_off"   # path to the data
snow_files <- dir(snow_path, pattern = "*.csv") # get file names
```

```{r}
snow_data <- snow_files %>%
  # read in all the files, appending the path before the filename
  map(~ read_csv(file.path(snow_path, .))) %>% 
  reduce(rbind)
snow_data
```

```{r}
snow_data %>% summarise_all(~ sum(is.na(.)))
```

```{r}
snow_sel = snow_data %>% 
                      dplyr::select(ID_obj:year) 
head(snow_sel)
```

## Combine Temp Precip and snow

```{r}
df_climate = merge(df_temp_pr, snow_sel, by = c("ID_obj", "area_ha", "area_m", "fire_yr"))

```

```{r}
df_climate
```

```{r}
df_climate %>% summarise_all(~ sum(is.na(.)))
```

```{r}
na_data <- df_climate %>% filter_all(any_vars(is.na(.))) 
na_data
```

# Clean data
- Remove NA
- Scale temperature data

```{r}
df_climate1 = df_climate %>% 
  na.omit() %>%
  mutate(temp_scale = 0.1) %>%
  mutate(wtr_temp = wtr_temp*temp_scale, .keep = "none") %>%
  mutate(spr_temp = spr_temp*temp_scale, .keep = "none") %>%
  mutate(smr_temp = smr_temp*temp_scale, .keep = "none") %>%
  dplyr::select(-temp_scale, -.keep)

df_climate1
```

# Visualize data